export const actions_s = [
    { id: 1, str1: '', str2: 'lance sa chaîne YouTube' },
    { id: 2, str1: '', str2: 'a créé une chaîne Twitch' },
    { id: 3, str1: '', str2: 'vient de devenir millionnaire' },
    { id: 4, str1: '', str2: 'déclare être officiellement raciste' },
    { id: 5, str1: '', str2: 'vote extrême droite' },
    { id: 6, str1: '', str2: 'a raté son baccalauréat' },
    { id: 7, str1: '', str2: 'a été viré de son emploi' },
    { id: 8, str1: '', str2: 'affirme avoir acheté son diplôme sur Snap' },
    { id: 9, str1: '', str2: 'repasse le brevet' },
    { id: 10, str1: '', str2: 'affirme avoir trouvé ce qu\'il lui fallait' },
    { id: 11, str1: '', str2: 'aime les mineures' },
    { id: 12, str1: '', str2: 'travaille sur la création d\'un album' },
    { id: 13, str1: '', str2: 'va sortir une nouvelle mixtape' },
    { id: 14, str1: 'Selon des sources,', str2: 'aurait rejoint la structure Karmine Corp' },
    { id: 15, str1: '', str2: 'a été pris en flagment délire' },
    { id: 16, str1: '', str2: 'devient officiellement un pessi' },
    { id: 17, str1: '', str2: 'a annoncé qu\'il souhaitait déménager au Listenbourg' },
    { id: 18, str1: 'Des rumeurs indiquent que', str2: 'signerait un accord avec le PSG' },
    { id: 19, str1: '', str2: 'serait en négociations directes avec le Real Madrid' },
    { id: 20, str1: 'D\'après sa déclaration,', str2: 'est en accord avec les propos de Kanye West' },
    { id: 21, str1: '', str2: 'a été arrêté pour possession de photographies de Grimkujow' },
    { id: 22, str1: '', str2: 'a déclaré qu\'il supporte la cause LGBTQIA+' },
    { id: 23, str1: '', str2: 'est actuellement incarcéré en prison' },
];