export const persons_s = [
    { id: 1, str: 'Grimkujow' },
    { id: 2, str: 'Maxime Biaggi' },
    { id: 3, str: 'Terracid' },
    { id: 4, str: 'Billy' },
    { id: 5, str: 'Aminematue' },
    { id: 6, str: 'Sefy' },
    { id: 7, str: 'Kameto' },
    { id: 8, str: 'Domingo' },
    { id: 9, str: 'Maghla' },
    { id: 10, str: 'Inoxtag' },
    { id: 11, str: 'Michou' },
    { id: 12, str: 'Djilsi' },
    { id: 13, str: 'Théodort' },
    { id: 14, str: 'Mastu' },
    { id: 15, str: 'Kaatsup' },
    { id: 16, str: 'Squeezie' },
    { id: 17, str: 'Cyprien' },
    { id: 18, str: 'Theomcx' },
    { id: 19, str: 'Cpastibo' },
    { id: 20, str: 'Zizou' },
    { id: 21, str: 'Chabert' },
    { id: 22, str: 'Rayhackerman' },
    { id: 23, str: 'Frappeur' },
    { id: 24, str: 'Emmanuel Macron' },
    { id: 25, str: 'Éric Zemmour' },
    { id: 26, str: 'Marine Le Pen' },
    { id: 27, str: 'Jean-Luc Mélenchon' },
    { id: 28, str: 'Jean Castex' },
    { id: 29, str: 'Jean-Michel Blanquer' },
    { id: 30, str: 'Jamel Debbouze' },
    { id: 31, str: 'Jonathan Cohen' },
    { id: 32, str: 'Pierre Niney' },
    { id: 33, str: 'Kev Adams' },
    { id: 34, str: 'Jean Dujardin' },
    { id: 35, str: 'Aya Nakamura' },
    { id: 36, str: 'Wejdene' },
    { id: 37, str: 'Damso' },
    { id: 38, str: 'Ninho' },
    { id: 39, str: 'Niska' },
    { id: 40, str: 'Booba' },
    { id: 41, str: 'Soprano' },
    { id: 42, str: 'Nekfeu' },
    { id: 43, str: 'Koba La D' },
    { id: 44, str: 'Ziak' },
    { id: 45, str: 'Lomepal' },
    { id: 46, str: 'Lorenzo' },
    { id: 47, str: 'Kerchak' },
    { id: 48, str: 'Kylian Mbappé' },
    { id: 49, str: 'Paul Pogba' },
    { id: 50, str: 'Neymar' },
    { id: 51, str: 'Cristiano Ronaldo' },
    { id: 52, str: 'Lionel Messi' },
    { id: 53, str: 'Karim Benzema' },
];